platform: linux
image_resource:
  type: docker-image
  source: {repository: alpine/git}
inputs:
- name: sample-app-branch
- name: sample-app-manifest
outputs:
- name: changed-manifest
run:
  path: sh
  args:
    - -exc
    - |
      tag=`cat sample-app-branch/.git/logs/refs/remotes/origin/HEAD | cut -d ' ' -f 2`
      git clone sample-app-manifest changed-manifest
      sed -i 's/image: 796489341143.*/image: 796489341143.dkr.ecr.ap-northeast-1.amazonaws.com\/sample-app:'${tag}'/g' changed-manifest/manifest.yml
      cd changed-manifest
      git config --global user.name "IshizuYuya"
      git config --global user.email "Ishizu.Yuya@ap.MitsubishiElectric.co.jp"
      git add -A
      git commit -m "update manifest"
